services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ClientActivity:
    class: App\Admin\ClientActivityAdmin
    arguments: [~, App\Entity\ClientActivity, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: ClientActivity, group: Parameters }

  Users:
    class: App\Admin\UserAdmin
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User, group: Users }

  Actions:
    class: App\Admin\ActionsAdmin
    arguments: [ ~, App\Entity\Action, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Actions, group: Actions }

  ActionsType:
    class: App\Admin\ActionTypeAdmin
    arguments: [ ~, App\Entity\ActionType, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: ActionsType, group: Actions }