services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ClientActivity:
    class: App\Admin\ClientActivityAdmin
    arguments: [~, App\Entity\ClientActivity, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: ClientActivity, group: Clients }

  Client:
    class: App\Admin\ClientAdmin
    arguments: [ ~, App\Entity\Client, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Clients, group: Clients }

  Users:
    class: App\Admin\UserAdmin
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User, group: Users }

  Actions:
    class: App\Admin\ActionAdmin
    arguments: [ ~, App\Entity\Action, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Actions, group: Actions }

  Devis:
    class: App\Admin\DevisAdmin
    arguments: [ ~, App\Entity\Devis, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Devis, group: Transactions }

  Invoices:
    class: App\Admin\InvoiceAdmin
    arguments: [ ~, App\Entity\Invoice, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Invoices, group: Transactions }

  Exchanges:
    class: App\Admin\ExchangeAdmin
    arguments: [ ~, App\Entity\Exchange, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Exchanges, group: Transactions }