services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ClientActivity:
    class: App\Admin\ClientActivityAdmin
    arguments: [~, App\Entity\ClientActivity, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: ClientActivity, group: Clients }

  Client:
    class: App\Admin\ClientAdmin
    arguments: [ ~, App\Entity\Client, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: ClientActivity, group: Clients }

  Users:
    class: App\Admin\UserAdmin
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User, group: Users }
