name: Api CRM

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.install-dependencies.outputs }}
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --with-dependencies

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - id: install-dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Run test unit
          run: |
            php vendor/bin/codecept run unit
        - name: Run test functional
          run: |
            php vendor/bin/codecept run functional